# ─── Hints Cache ──────────────────────────────────────────────────────────────
# Persistent cache of all rules from the Wallarm API.
# Refresh on import or explicit request. Otherwise reads from state.

module "hints_cache" {
  source = "./modules/hints_cache"

  client_id            = var.client_id
  refresh              = var.is_importing
  rule_types           = var.import_rule_types
  configs_dir          = var.configs_dir
  rules_engine_address = var.rules_engine_address
}

# ─── Import blocks ───────────────────────────────────────────────────────────
# Generated from hints_cache when importing. Written to a .tf file so Terraform
# can read them at plan time.

resource "local_file" "import_blocks" {
  count           = var.is_importing && module.hints_cache.import_blocks_content != "" ? 1 : 0
  filename        = "${path.root}/wallarm_rule_imports.tf"
  file_permission = "0644"
  content         = module.hints_cache.import_blocks_content
}

# ─── Fetch hits and generate rule objects ─────────────────────────────────────

module "hits" {
  for_each = var.requests
  source   = "./modules/hits_fetcher"

  client_id  = var.client_id
  request_id = each.key
  rule_types = each.value
  config_dir = var.configs_dir
  mode       = var.hits_mode

  # Gate: fetch from API when explicitly requested or when no hits YAML files exist.
  fetch_hits = var.fetch_hits || length(try(fileset(var.configs_dir, "**/hits_*.yaml"), toset([]))) == 0
}

locals {
  # Import is ready on second apply — import blocks file exists from first apply.
  _import_ready = var.is_importing && fileexists("${path.root}/wallarm_rule_imports.tf")
}

# ─── Unified rules engine ────────────────────────────────────────────────────
# Reads YAML configs from disk + generated_rules from hits and imports.

module "rules" {
  source = "./modules/rules_engine"

  client_id = var.client_id

  config_dirs = [var.configs_dir]

  generated_rules = concat(
    # Rules from hits
    flatten([for req_id in keys(var.requests) : module.hits[req_id].rules]),
    # Rules from import (via hints_cache) — only when import blocks file already exists.
    # First apply (-var='import_rules=true'): writes import blocks file only.
    # Second apply (-var='import_rules=true'): import blocks present → resource blocks + import.
    # YAML files are generated by rules_engine from generated_rules on the second apply.
    local._import_ready ? module.hints_cache.import_rules : [],
  )
}

# ─── Action .yaml from import ─────────────────────────────────────────────────
# Write .action.yaml for each unique action directory from imported rules.
# wallarm_config_file: state-only delete → file persists on disk.

resource "wallarm_config_file" "action_configs" {
  for_each = local._import_ready ? module.hints_cache.action_dirs : {}

  path = "${var.configs_dir}/${each.value.dir_name}/.action.yaml"
  content = yamlencode({
    conditions_hash = each.value.conditions_hash
    action_id       = each.value.action_id
  })

  lifecycle {
    ignore_changes = [content]
  }
}

# ─── Action discovery (separate step) ────────────────────────────────────────
# Discovers new action scopes from API and generates .action.yaml files.
# Run with: terraform apply -var='discover_actions=true'

data "wallarm_actions" "discovery" {
  count     = var.discover_actions ? 1 : 0
  client_id = var.client_id
}

locals {
  known_action_hashes = { for hash, cfg in module.rules.action_map : hash => true }

  discovered_actions = var.discover_actions ? {
    for a in try(data.wallarm_actions.discovery[0].actions, []) :
    a.conditions_hash => a
    if !contains(keys(local.known_action_hashes), a.conditions_hash)
  } : {}
}

resource "local_file" "discovered_action_config" {
  for_each = local.discovered_actions

  filename        = "${var.configs_dir}/${each.value.dir_name}/.action.yaml"
  file_permission = "0644"

  content = yamlencode({
    conditions      = each.value.conditions
    conditions_hash = each.value.conditions_hash
    action_id       = each.value.action_id
    action_path     = each.value.endpoint_path
    action_domain   = each.value.endpoint_domain
    action_instance = each.value.endpoint_instance
  })

  lifecycle {
    ignore_changes = [content]
  }
}
